apiVersion: apps/v1
kind: Deployment
metadata:
  name: matches-service
  namespace: snooker-livescore
  labels:
    app: matches-service
    component: data-read
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matches-service
  template:
    metadata:
      labels:
        app: matches-service
        component: data-ingestion
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8088"
    spec:
      containers:
      - name: matches-service
        image: astoyanov87/matches-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8088
          name: health
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
        env:
        - name: REDIS_HOST
          value: "192.168.100.84"
        - name: REDIS_PORT
          value: "6379"
        livenessProbe:
          httpGet:
            path: /health
            port: health
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10