apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matches-ingress
  namespace: snooker-livescore
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: snooker-livescore.local.dev
      http: 
        paths:
        - path: /api/v1/swagger/
          pathType: Prefix
          backend:
            service:
              name: matches
              port:
                number: 80
