apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: matches-ingress
  namespace: snooker-livescore
spec:
  ingressClassName: traefik
  rules:
    - host: snookerscores.org
      http:
        paths:
        - path: /api/v1
          pathType: Prefix
          backend:
            service:
              name: matches
              port:
                number: 80
        - path: /api/v1/swagger
          pathType: Prefix
          backend:
            service:
              name: matches
              port:
                number: 80
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ui-service
              port:
                number: 80
